name 'puppet-make_apt_repo'
version '0.1'
source 'git://github.com/AdnanHodzic/puppet-make_apt_repo.git'
author 'AdnanHodzic, jtopjian, saz, camptocamp'
license 'Apache 2.0'
summary 'Your local apt reposistory assistant.'
description 'Puppet module which assists you with creation of your local apt reposistory.'
project_page 'https://github.com/jtopjian/puppet-reprepro'
dependency 'ripienaar/concat', '>=0.2.0'
